include:
  - ./docker-compose-base.yml

name: wenruo-rag

services:
  wenruo-rag-cpu:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        WEB_DIST_MODE: ${WEB_DIST_MODE:-build}
        SOURCE_COMMIT: ${SOURCE_COMMIT:-local}
        WEB_BUILD_HEAP_MB: ${WEB_BUILD_HEAP_MB:-4096}
    image: ${RAGFLOW_IMAGE:-my-wenruorag:latest}
    container_name: wenruo-rag-cpu
    depends_on:
      mysql:
        condition: service_healthy
        required: false
      nats:
        condition: service_healthy
        required: false
    profiles:
      - cpu
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc:
        soft: 65535
        hard: 65535
    command:
      - --enable-adminserver
      - --init-model-provider-tables
    ports:
      - ${SVR_WEB_HTTP_PORT}:80
      - ${SVR_WEB_HTTPS_PORT}:443
      - ${SVR_HTTP_PORT}:9380
      - ${ADMIN_SVR_HTTP_PORT}:9381
      - ${SVR_MCP_PORT}:9382
      - ${GO_HTTP_PORT}:9384
      - ${GO_ADMIN_PORT}:9383
    environment:
      - SANDBOX_EXECUTOR_MANAGER_API_TOKEN=${SANDBOX_EXECUTOR_MANAGER_API_TOKEN:-}
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./entrypoint.sh:/ragflow/entrypoint.sh
    env_file: .env
    networks:
      - ragflow
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wenruo-rag-gpu: # 服务名修改
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        WEB_DIST_MODE: ${WEB_DIST_MODE:-build}
        SOURCE_COMMIT: ${SOURCE_COMMIT:-local}
        WEB_BUILD_HEAP_MB: ${WEB_BUILD_HEAP_MB:-4096}
    image: ${RAGFLOW_IMAGE:-my-wenruorag:latest} # 镜像名修改
    container_name: wenruo-rag-gpu                # 容器名修改
    depends_on:
      mysql:
        condition: service_healthy
        required: false
      nats:
        condition: service_healthy
        required: false
    profiles:
      - gpu
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc:
        soft: 65535
        hard: 65535
    command:
      - --enable-adminserver
    ports:
      - ${SVR_WEB_HTTP_PORT}:80
      - ${SVR_WEB_HTTPS_PORT}:443
      - ${SVR_HTTP_PORT}:9380
      - ${ADMIN_SVR_HTTP_PORT}:9381
      - ${SVR_MCP_PORT}:9382
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./entrypoint.sh:/ragflow/entrypoint.sh
    environment:
      - SANDBOX_EXECUTOR_MANAGER_API_TOKEN=${SANDBOX_EXECUTOR_MANAGER_API_TOKEN:-}
    env_file: .env
    networks:
      - ragflow
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]